[env]
PROJECT_NAME = "ai-playbook"

[tools]
gh = "2.93"
gitversion = "6.7"
"pipx:pre-commit" = "4.6"
uv = "0.11"

[task_config]
includes = [
  "git::ssh://git@github.com/jterral/my-mise-tasks.git//tasks/precommit",
]
